version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build-and-test:
    environment:
      CODECOV_TOKEN: a9097475-0b5b-481f-8733-7b84574d583e
    docker:
      - image: circleci/node:14.17.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: set GIT name and email
          command: |
            git config --global -l
            git config --global user.email "$GIT_COMMITTER_EMAIL"
            git config --global user.name "$GIT_COMMITTER_NAME"
            git config --global -l
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - strapi-plugin-navigation-v1-{{ checksum "yarn.lock" }}
            - strapi-plugin-navigation-
      - run:
          name: Echo versions
          command: |
            node --version
            yarn --version
      - run:
          name: Install
          command: |
            yarn install
      - run:
          name: Test
          command: |
            yarn test:unit
      - codecov/upload:
          flags: unittest
          file:
      - save_cache:
          paths:
            - ./node_modules
          key: strapi-plugin-navigation-v1-{{ checksum "yarn.lock" }}
workflows:
    build-and-test:
      jobs:
        - build-and-test
