const en = {
  plugin: {
    name: 'Navegación UI',
    section: {
      name: 'Plugin de navegación',
      item: 'Configuración',
    },
  },
  header: {
    title: 'Navegación',
    description: 'Define la navegación de tu portal',
    meta: 'ID: { id }, slug: { key }',
    action: {
      newItem: 'Nuevo ítem',
      manage: 'Gestionar',
      collapseAll: 'Colapsar todo',
      expandAll: 'Expandir todo',
    },
  },
  submit: {
    cta: {
      cancel: 'Cancelar',
      save: 'Guardar',
    },
  },
  empty: {
    description: 'Tu navegación está vacía',
    cta: 'Crear primer ítem',
  },
  popup: {
    navigation: {
      manage: {
        header: {
          LIST: 'Todas las navegaciones',
          CREATE: 'Nueva navegación',
          DELETE: 'Eliminando',
          ERROR: 'Error',
          EDIT: 'Editando "{name}"',
        },
        button: {
          cancel: 'Cancelar',
          delete: 'Eliminar',
          save: 'Guardar',
          edit: 'Edit',
          create: 'Create',
          goBack: 'Volver',
          purge: 'Borrar caché de lectura',
        },
        table: {
          id: 'Id',
          name: 'Nombre',
          locale: 'Versiones de idioma',
          visibility: 'Visibilidad',
          hasSelected: '{count} entradas seleccionadas',
        },
        footer: {
          button: {
            purge: 'Clear',
          },
        },
        purge: {
          header:
            'Esta acción limpiará la caché de lectura de la API. Esto puede causar una breve ralentización en las lecturas de las navegaciones siguientes.',
        },
        delete: {
          header: 'Las siguientes navegaciones serán eliminadas:',
        },
        error: {
          header: 'Ocurrió un error :(',
          message: 'Ocurrió un error al procesar la solicitud.',
        },
        navigation: {
          visible: 'visible',
          hidden: 'oculto',
        },
      },
      form: {
        name: {
          label: 'Nombre',
          placeholder: "Navigations's name",
          validation: {
            name: {
              required: 'El nombre es obligatorio',
              tooShort: 'El nombre es demasiado corto',
              alreadyUsed: 'El nombre ya está en uso',
            },
            visible: {
              required: 'La visibilidad es obligatoria',
            },
          },
        },
        visible: {
          label: 'Visibilidad',
          toggle: {
            visible: 'Visible',
            hidden: 'Hidden',
          },
        },
      },
    },
    item: {
      header: {
        view: 'Ver ítem de navegación',
        edit: 'Editar ítem de navegación',
        new: 'Nuevo ítem de navegación',
      },
      form: {
        title: {
          label: 'Título',
          autoSync: {
            label: 'Leer campos relacionados',
          },
          placeholder:
            'Introduce el título del ítem o déjalo en blanco para extraerlo de la entidad relacionada',
        },
        uiRouterKey: {
          label: 'Clave de UI Router',
          placeholder: 'If empty, auto generated by "Título"',
        },
        uiRouter: {
          unableToRender:
            'No se puede generar el slug y/o la clave de UI Router debido a caracteres no admitidos',
        },
        path: {
          label: 'URL',
          placeholder: 'Parte única del URL que identifica este ítem',
          preview: 'Vista previa:',
        },
        externalPath: {
          label: 'URL externa',
          placeholder: 'Enlace a la fuente externa',
          validation: {
            type: 'Este valor no es una URL válida.',
          },
        },
        menuAttached: {
          label: 'Adjuntar al menú',
          value: {
            yes: 'Sí',
            no: 'No',
          },
        },
        type: {
          label: 'Tipo de ítem de navegación',
          internal: {
            label: 'Fuente interna',
          },
          external: {
            label: 'Fuente externa',
            description: 'Ruta de salida: {value}',
          },
          wrapper: {
            label: 'Elemento contenedor',
          },
        },
        audience: {
          label: 'Audiencia',
          placeholder: 'Seleccionar audiencia...',
          empty: 'No hay más audiencias disponibles',
        },
        relatedSection: {
          label: 'Relación con',
        },
        relatedType: {
          label: 'Tipo de contenido',
          placeholder: 'Seleccionar tipo de contenido...',
          empty: 'No hay tipos de contenido para seleccionar',
        },
        related: {
          label: 'Entidad',
          placeholder: 'Seleccionar entidad...',
          empty: 'No hay más entidades de "{ contentTypeName }" para seleccionar',
        },
        i18n: {
          locale: {
            label: 'Copiar detalles de',
            placeholder: 'Idioma',
            button: 'Copiar',
            error: {
              generic: 'No se pudo copiar el ítem',
              unavailable: 'Versión de idioma no disponible',
            },
          },
        },
        button: {
          create: 'Crear ítem',
          update: 'Actualizar ítem',
          restore: 'Restaurar ítem',
          remove: 'Eliminar',
          save: 'Guardar',
          cancel: 'Cancelar',
        },
      },
    },
  },
  notification: {
    navigation: {
      submit: 'Los cambios en la navegación han sido guardados',
      error: 'Ruta duplicada: "{ path }" en el padre: "{ parentTitle }" para { errorTitles } ítems',
      item: {
        relation: '¡La relación de la entidad no existe!',
        status: {
          draft: 'borrador',
          published: 'publicado',
        },
      },
    },
    error: {
      common: 'Error al procesar la solicitud.',
      customField: {
        type: 'Tipo de campo personalizado no compatible',
        media: {
          missing: 'Falta el componente de entrada de medios',
        },
      },
      item: {
        relation: 'Las relaciones proporcionadas en algunos ítems son incorrectas',
        slug: 'No se pudo crear una clave de UI Router válida (slug) a partir de "{ query }". Se recibió "{ result }"',
      },
    },
  },
  pages: {
    auth: {
      noAccess: 'Sin acceso',
      not: {
        allowed: '¡Ups! Parece que no tienes acceso a esta página...',
      },
    },
    main: {
      search: {
        placeholder: 'Escribe para comenzar la búsqueda...',
        subLabel: 'presiona ENTER para resaltar el siguiente ítem',
      },
      header: {
        localization: {
          select: {
            placeholder: 'Seleccionar idioma',
          },
        },
      },
    },
    settings: {
      title: 'Configuración de navegación',
      general: {
        title: 'Configuración general',
      },
      additional: {
        title: 'Configuraciones adicionales',
      },
      customFields: {
        title: 'Configuraciones de campos personalizados',
      },
      nameField: {
        title: 'Configuración de tipos de contenido',
      },
      restoring: {
        title: 'Restauración',
      },
      section: {
        title: 'Plugin de navegación',
        subtitle: 'Configuración',
      },
      header: {
        title: 'Navegación',
        description: 'Configura el plugin de navegación',
      },
      form: {
        cascadeMenuAttached: {
          label: 'Menú en cascada adjunto',
          hint: 'Deshabilitar si no deseas que "Menú adjunto" se propague a los elementos secundarios',
        },
        preferCustomContentTypes: {
          label: 'Preferir tipos de contenido de API',
          hint: 'Preferir si se desea usar solo tipos de contenido con prefijo api::',
        },
        contentTypes: {
          label: 'Habilitar navegación para',
          placeholder: 'Ejemplo: Páginas, Publicaciones',
          hint: 'Si no se selecciona ninguno, ninguno de los tipos de contenido estará habilitado',
        },
        i18n: {
          label: 'i18n',
          hint: 'Habilitar internacionalización',
          hintMissingDefaultLocale: '¡Idioma predeterminado faltante!',
        },
        allowedLevels: {
          label: 'Niveles permitidos',
          placeholder: 'Ejemplo: 2',
          hint: 'Nivel máximo en el que puedes marcar un ítem como "Menú adjunto"',
        },
        audience: {
          label: 'Audiencia',
          hint: 'Habilitar campo de audiencia',
        },
        nameField: {
          default: 'Predeterminado',
          label: 'Campos de nombre',
          placeholder:
            'Selecciona al menos uno o deja en blanco para aplicar los valores predeterminados',
          hint: 'Si se deja en blanco, el campo de nombre tomará los siguientes campos en orden: "título", "asunto" y "nombre"',
          empty: 'Este tipo de contenido no tiene atributos de tipo cadena',
        },
        populate: {
          label: 'Campos a completar',
          placeholder:
            'Selecciona al menos uno o deja en blanco para deshabilitar la población de campos de relación',
          hint: 'Los campos de relación seleccionados se completarán dentro de las respuestas de la API',
          empty: 'Este tipo de contenido no tiene campos de relación',
        },
        pathDefaultFields: {
          label: 'Campos predeterminados de ruta',
          placeholder:
            'Selecciona al menos uno o déjalo vacío para deshabilitar la población de la ruta con valores de atributos',
          hint: 'El valor del atributo seleccionado será el valor predeterminado para la ruta interna',
          empty: 'Este tipo de contenido no tiene atributos adecuados',
        },
        contentTypesSettings: {
          label: 'Tipos de contenido',
          tooltip: 'Configuración personalizada por tipo de contenido',
          initializationWarning: {
            title: 'Advertencia',
            content:
              '- El tipo de contenido aún no ha sido inicializado. Inicialízalo primero para poder usarlo en el editor visual.',
          },
        },
        customFields: {
          table: {
            confirmation: {
              header: 'Eliminando campo personalizado',
              message:
                'Esta acción eliminará todos los valores de campos personalizados de los elementos de navegación.',
              confirm: 'Continuar',
              error: 'Ocurrió un error al eliminar el campo personalizado',
            },
            header: {
              name: 'Nombre',
              label: 'Etiqueta',
              type: 'Tipo',
              required: 'Requerido',
            },
            footer: 'Crear nuevo campo personalizado',
            edit: 'Editar campo personalizado',
            enable: 'Habilitar campo personalizado',
            disable: 'Deshabilitar campo personalizado',
            remove: 'Eliminar campo personalizado',
            required: 'requerido',
            notRequired: 'no requerido',
          },
          popup: {
            header: {
              edit: 'Editar campo personalizado',
              new: 'Añadir nuevo campo personalizado',
            },
            name: {
              label: 'Nombre del campo personalizado',
              placeholder: 'ejemplo_nombre',
              description: 'El nombre del campo personalizado debe ser único',
            },
            label: {
              label: 'Etiqueta del campo personalizado',
              placeholder: 'Ejemplo de etiqueta',
              description: 'Esta etiqueta se mostrará en el formulario del elemento de navegación',
            },
            type: {
              label: 'Tipo de campo personalizado',
              description: 'El tipo de campo personalizado define cómo se mostrará',
            },
            required: {
              label: 'Campo obligatorio',
              description:
                'Habilitar este campo no cambiará los elementos de navegación ya existentes',
            },
            options: {
              label: 'Opciones para la entrada de selección',
              description: 'Proporciona opciones separadas por ";"',
            },
            multi: {
              label: 'Habilitar entrada de múltiples opciones',
              description: 'Permitir selección única o múltiple',
            },
          },
        },
      },
      actions: {
        submit: 'Guardar configuración',
        restore: {
          label: 'Restaurar configuración',
          confirmation: {
            header: '¿Quieres continuar?',
            confirm: 'Restaurar',
            description: 'La configuración del plugin se restaurará desde el archivo plugins.js.',
          },
          description:
            'Restaurar la configuración del plugin causará que sea reemplazada con la configuración guardada en el archivo "plugins.js".',
        },
        restart: {
          label: 'Reiniciar Strapi',
          alert: {
            title: 'Strapi requiere reinicio',
            description:
              'Has realizado cambios en la configuración que requieren que Strapi se reinicie para que surtan efecto. Hazlo manualmente o usa el siguiente disparador.',
            close: 'Descartar',
            cancel: 'Cancelar',
            reason: {
              I18N: 'Se aplicarán cambios de internacionalización (i18n).',
              GRAPH_QL: 'Se aplicarán cambios de GraphQL.',
              I18N_NAVIGATIONS_PRUNE: 'Se eliminarán navegaciones obsoletas de idioma.',
            },
          },
        },
        disableI18n: {
          confirmation: {
            header: 'Deshabilitando Internacionalización',
            confirm: 'Entiendo',
            description: {
              line1:
                'Estás deshabilitando la Internacionalización para la Navegación. Las navegaciones en idiomas distintos al predeterminado no estarán disponibles para ver y modificar a través de este plugin.',
              line2: 'Puedes elegir eliminar las navegaciones para otros idiomas.',
              line3: '¡Recuerda! La eliminación es irreversible',
            },
          },
          prune: {
            label: 'Navegaciones obsoletas',
            on: 'Eliminar',
            off: 'Mantener',
          },
        },
      },
      notification: {
        fetch: {
          error: 'Error al obtener la configuración. Reintentando...',
        },
        submit: {
          success: 'La configuración se ha actualizado correctamente',
          error: 'Error al actualizar la configuración',
        },
        restore: {
          success: 'La configuración se ha restaurado correctamente',
          error: 'Error al restaurar la configuración',
        },
        restart: {
          success: 'La aplicación se ha reiniciado correctamente',
          error: 'Error al reiniciar la aplicación. Intenta hacerlo manualmente.',
        },
      },
    },
    view: {
      actions: {
        i18nCopyItems: {
          confirmation: {
            header: 'Confirmación',
            confirm: 'Copiar',
            content: '¿Quieres copiar los elementos de navegación?',
          },
        },
      },
    },
  },
  components: {
    toggle: {
      enabled: 'Habilitado',
      disabled: 'Deshabilitado',
    },
    navigationItem: {
      action: {
        newItem: 'Agregar elemento anidado',
        edit: 'Editar',
        view: 'Ver',
        restore: 'Restaurar',
        remove: 'Eliminar',
      },
      badge: {
        removed: 'Eliminado',
        draft: 'Borrador',
        published: 'Publicado',
      },
      related: {
        localeMissing: '(Versión de idioma faltante)',
      },
    },
    confirmation: {
      dialog: {
        button: {
          cancel: 'Cancelar',
          confirm: 'Confirmar',
        },
        description: '¿Quieres continuar?',
        header: 'Confirmación',
      },
    },
    notAccessPage: {
      back: 'Volver a la página de inicio',
    },
  },
  view: {
    i18n: {
      fill: {
        option: '{locale} idioma',
        cta: {
          header: 'o iniciar',
          button: 'copiar',
        },
      },
    },
  },
};

export default en;

export type EN = typeof en;
