"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getNavigationRepository = exports.getNavigationItemRepository = exports.getGenericRepository = exports.getAudienceRepository = void 0;
var audience_1 = require("./audience");
Object.defineProperty(exports, "getAudienceRepository", { enumerable: true, get: function () { return audience_1.getAudienceRepository; } });
var generic_1 = require("./generic");
Object.defineProperty(exports, "getGenericRepository", { enumerable: true, get: function () { return generic_1.getGenericRepository; } });
var navigation_item_1 = require("./navigation-item");
Object.defineProperty(exports, "getNavigationItemRepository", { enumerable: true, get: function () { return navigation_item_1.getNavigationItemRepository; } });
var navigation_1 = require("./navigation");
Object.defineProperty(exports, "getNavigationRepository", { enumerable: true, get: function () { return navigation_1.getNavigationRepository; } });
