export const GET_LIST_DATA = "GET_LIST_DATA";
export const GET_LIST_DATA_SUCCEEDED = "GET_LIST_DATA_SUCCEEDED";
export const GET_NAVIGATION_DATA = "GET_NAVIGATION_DATA";
export const GET_NAVIGATION_DATA_SUCCEEDED = "GET_NAVIGATION_DATA_SUCCEEDED";

export const CHANGE_NAVIGATION_DATA = "CHANGE_NAVIGATION_DATA";
export const RESET_NAVIGATION_DATA = "RESET_NAVIGATION_DATA";

export const CHANGE_NAVIGATION_POPUP_VISIBILITY =
  "CHANGE_NAVIGATION_POPUP_VISIBILITY";
export const CHANGE_NAVIGATION_ITEM_POPUP_VISIBILITY =
  "CHANGE_NAVIGATION_ITEM_POPUP_VISIBILITY";

export const GET_CONTENT_TYPE_ITEMS = "GET_CONTENT_TYPE_ITEMS";
export const GET_CONTENT_TYPE_ITEMS_SUCCEEDED =
  "GET_CONTENT_TYPE_ITEMS_SUCCEEDED";

export const GET_CONFIG = "GET_CONFIG";
export const GET_CONFIG_SUCCEEDED = "GET_CONFIG_SUCCEEDED";

export const SUBMIT_NAVIGATION = "SUBMIT_NAVIGATION";
export const SUBMIT_NAVIGATION_SUCCEEDED = "SUBMIT_NAVIGATION_SUCCEEDED";
export const SUBMIT_NAVIGATION_ERROR = "SUBMIT_NAVIGATION_ERROR";


export const RELOAD_PLUGIN = "RELOAD_PLUGIN";
